name: deploy

on: 
  push:
    branches: [main]

jobs:
  get-the-code:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout Code
         uses: actions/checkout@v4
        
       - name: Configure AWS Creds
         uses: aws-actions/configure-aws-credintial@v1
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
           aws-region: eu-west-1

       - name: Deploy
         run: aws s3 sync . s3://personal-portfolio-bucket-by-rushikesh-github-actions --delete
      
